Fix: TypeScript error in zip generation
The TypeScript error TS2353: Object literal may only specify known properties, and 'onUpdate' does not exist in type 'JSZipGeneratorOptions<"blob">'.  was fixed.